// This file was generated by lezer-generator. You probably shouldn't edit it.
module.exports = {
  Contents: 1,
  Tag: 2,
  TagStart: 3,
  Attr: 4,
  TagName: 5,
  ContentsStart: 6,
  TagEnd: 7,
  Other: 8
}