// This file was generated by lezer-generator. You probably shouldn't edit it.
const {Parser} = require("lezer")
const {NodeProp} = require("lezer")
exports.parser = Parser.deserialize({
  version: 13,
  states: "&fQQOPOOOcOQO'#C^OOOO'#Ck'#CkOOOO'#Ci'#CiOOOO'#Ce'#CeQQOPOOOOOO'#Cf'#CfOnOQO,58xOyOQO,58xO!XOPO,58xOOOO-E6c-E6cOOOO-E6d-E6dO!^OQO1G.dO!lOPO1G.dO!^OQO1G.dO!qOQO'#CgO#POPO1G.dOOOO1G.d1G.dO#[OPO1G.dO#cOQO7+$OO#qOPO7+$OOOOO7+$O7+$OO#|OPO7+$OO#cOQO7+$OO$TOQO,59ROOOO-E6e-E6eO#|OPO7+$OO$cOPO<<GjOOOO<<Gj<<GjO$nOPO<<GjO$nOPO<<GjO$uOQO<<GjOOOOAN=UAN=UO%TOPOAN=UO%TOPOAN=UO%[OPOAN=UOOOOG22pG22pO%gOPOG22pO%gOPOG22pOOOOLD([LD([O%nOPOLD([OOOO!$'Kv!$'Kv",
  stateData: "%w~ORPOSQOTQOUQOWQO~OSXOTWO^UO~OS]OT[O^UO~ORPOUbOVaO^UO~OT[O~ORPOUfOVeO^UO~OTgO~O^UORZXUZXVZX~ORPOUfOVeO~OVeO~PQORPOUmOVlO^UO~ORPOUmOVlO~OVlO~PQO^UORZaUZaVZa~ORPOUqOVpO~OVpO~PQORPOUqOVpO^UO~OVtO~PQORPOUvOVtO~OVwO~PQOVyO~PQOW~",
  goto: "$P`PPaPPPPPP{!g!}P#cP#qhROTbfjmnqruvxe_W[^`cdgkosQTO[YTjnruxQjbQnfQrmQuqRxvQVPYZV^choQ^WQc[Qh_RogQ`WSd[^Wi`dksSkcgRsoiSOTbfjmnqruvxiROTbfjmnqruvx",
  nodeNames: "⚠ Contents Tag TagStart Attr TagName ContentsStart TagEnd Other",
  maxTerm: 15,
  nodeProps: [
    [NodeProp.closedBy, 3,"TagEnd"],
    [NodeProp.openedBy, 7,"TagStart"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "%m~R`OX!TXY!fYp!Tpq!fq!Q!T!Q![!y![!]$q!]!b!T!b!c%O!c!}!y!}#T!T#T#o!y#o#p%c#p#q!T#q#r%h#r~!TP!YSWPO![!T!]#o!T#p#q!T#r~!TR!mS^QWPO![!T!]#o!T#p#q!T#r~!T~#Q[T~WPOX!TXY#vYp!Tpq#vq!Q!T!Q![!y!]!c!T!c!}!y!}#T!T#T#o!y#p#q!T#r~!T~#{[WPOX!TXY#vYp!Tpq#vq!Q!T!Q![!y!]!c!T!c!}!y!}#T!T#T#o!y#p#q!T#r~!T~$vPU~pq$y~%OOU~~%VSS~WPO![!T!]#o!T#p#q!T#r~!T~%hOR~~%mOV~",
  tokenizers: [0, 1],
  topRules: {"Contents":[0,1]},
  tokenPrec: 221
})
